
#ifndef __PARALLELH
#define __PARALLELH

#include "mpi.h"

const int TAG1 = 89;

// enum MESSAGE {KILL,SCAN,UPDATE_RATE,UPDATE_RRATE,UPDATE_BLENGTH,UPDATE_SRATE,UPDATE_SPROFILE,PARAMETER_DIFFUSION,UNFOLD,COLLAPSE,LIKELIHOOD,RESET,MULTIPLY,SMULTIPLY,INITIALIZE,PROPAGATE,PROPOSE,RESTORE,UPDATE,DETACH,ATTACH,NNI,KNIT,BRANCHPROPAGATE,ROOT,REALLOC_MOVE,PROFILE_MOVE,MIX_MOVE,REALLOC_DONE,GIVEMEMORE,BCAST_TREE,GETDIV,UNCLAMP,SETDATA,CVSCORE,SETTESTDATA,GENE_MOVE,SAMPLE,LENGTH,ALPHA,SAVETREES, LENGTHFACTOR, FROMSTREAM, TOSTREAM, SITELOGL, RESTOREDATA, WRITE_MAPPING};

struct prop_arg {
  double time;
  int condalloc;
  int to;
  int from;
};

#endif



